version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    env_file: 
      - .env
    image: postgres
    volumes:
      - db-data:/usr/local/pgsql/data

  app:
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

